
# the seeds are red from yaml generated by a rake task

File.open("db/seeds.yaml") do |yaml_file|
  seeds = YAML::load(yaml_file)
  seeds.each do |seed|
    puts seed
    Passage.create!(seed)
  end

end
